### ISSUE TITLE
Each catalog has a different color

### ISSUE THREAD

**Issue by trydofor** [antfu/vscode-pnpm-catalog-lens#6]
### Clear and concise description of the problem

```yaml
catalogs:
  common:     ## color:orange
    "@vueuse/core": "^11.0.3"
    "@vueuse/nuxt": "^11.0.3"
  deploy:     ## color:blue
    "@changesets/cli": "^2.27.8"
  testing:    ## color:green
    "vitest": "^2.0.5"
```

it would be great if catalog with different color to distinguish them.

### Suggested solution

color can auto calculate or manually set

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
